command_timeout = 10000

format = """
$hostname$directory$git_branch$git_status$status$cmd_duration
$character
"""

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = 'bold green'

[directory]
truncation_length = 3
truncate_to_repo = true
style = 'cyan'
format = ':/[$path]($style) '

[git_branch]
symbol = ''
style = 'purple'
format = '[$symbol$branch]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]](red) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged = "✚"
modified = "⚠"
untracked = "?"
stashed = "📦"
deleted = "✘"
conflicted = "⚔"

[status]
style = 'bold red'
symbol = '✗'
format = ' [$symbol $status]($style)'
disabled = false

[cmd_duration]
min_time = 2000  # show if command took > 2 seconds
format = '⏱ [$duration]($style)'
style = 'bold yellow'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
